### ISSUE TITLE
sensor_type as a table

### ISSUE THREAD

**Issue by mbredif** [LI3DS/pg-li3ds#6]
sensor_type is an enum, and transfo_type is a table. They are however kind of the same species. They both provide a way to translate a type `id` integer into its type information : `name`(func_name), `description`, `schema`(func_signature) for a jsonb attribute(`parameters` for transofs, `specifications` for sensors).

They could be both implemented similarly as a table. That would enable code reuse and enable extensibility for sensor types, and the ability to specify the schema of its jsonb attribute.

**Comment by elemoine** [comment]
Talking about that, who is responsible for populating `transfo_type`? I am currently trying to insert `transfo`'s through the API but I run into problems because there's no transfo type.

**Comment by mbredif** [comment]
My guess is that the responsible is the one that implements the transform_type or that creates the postgresql extension that adds the different transform implementations. This guy will also have to create the sql function that applies transfos and transfo stacks.

**Comment by elemoine** [comment]
Closing this for now. But please reopen if you care enough about this :)
