### ISSUE TITLE
Display geolocalized points in itowns 

### ISSUE THREAD

**Issue by ldgeo** [LI3DS/pg-li3ds#61]
exported as txt with PSQL, converted to las with PDAL and loaded into PostgreSQL with lopocs: 

it sounds good ! 

![li3ds_lopocs](https://user-images.githubusercontent.com/1412193/30265746-6921ca3e-96dd-11e7-8ea9-d9bbfce14859.png)

**Comment by ldgeo** [comment]
@mbredif @elemoine i think we can add this for demo

**Comment by elemoine** [comment]
That's great! I'll add a screenshot to the report.
