### ISSUE TITLE
cannot determine type of empty array 

### ISSUE THREAD

**Issue by mbredif** [LI3DS/pg-li3ds#62]
```
ERROR:  spiexceptions.IndeterminateDatatype: cannot determine type of empty array
LIGNE 12 :             and array[t.id] <@ array[]
                                          ^
ASTUCE : Explicitly cast to the desired type, for example ARRAY[]::integer[].
REQUÊTE : 
        select
            r.id
            , array_agg(t.target)
              filter (where t.target is not NULL) as adj_list
              -- we keep a NULL column instead of an array
              -- with a null value inside
        from li3ds.referential r
        left join li3ds.transfo t
            -- we only keep direct transformations
            on t.source = r.id
            and array[t.id] <@ array[]
        group by r.id        
CONTEXTE : Traceback (most recent call last):
  PL/Python function "transform", line 3, in <module>
    return pg_li3ds.transform_box4d_config(box4d, config, source, target, ttime)
  PL/Python function "transform", line 354, in transform_box4d_config
  PL/Python function "transform", line 117, in dijkstra
PL/Python function "transform"
```

**Comment by mbredif** [comment]
This error is triggered by the sql code in https://github.com/LI3DS/pg-li3ds/issues/60.

**Comment by elemoine** [comment]
You use a different query that the one in #60, so I am not sure I understand. If you need an empty array that is typed you can use `'{}'::int[]` for example.

**Comment by mbredif** [comment]
Nope i use that exact query. I guess the error is triggered within a function (dijkstra?)

**Comment by elemoine** [comment]
The code is different in Dijkstra. It uses `array[{}]` instead of `array[]` (see https://github.com/LI3DS/pg-li3ds/blob/master/python/pg_li3ds/__init__.py#L116). So I am not sure.

Are you sure you use the latest code? Can you please provide a simple query demonstrating the issue?

**Comment by elemoine** [comment]
I am hitting this issue as well. It occurs when attempting to restore an SQL dump of the li3ds database. Not sure why I am not seeing the issue when executing the query in #60.
